AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API de PageGear Mailer

Parameters:
  Environment:
    Type: String
    Default: Prod
  TimeOut:
    Type: Number
    Default: 300

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: HooksPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - logs:*
                - rds:*
                - lambda:*
                - ec2:*
                - ecs:*
                - s3:*
                - apigateway:*
                - execute-api:*
                - dynamodb:*
                - cloudwatch:*
                - sqs:*
                - sns:*
                - ses:*
                - iam:PassRole
              Resource: "*"

  PageGearMailerApiFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: PageGearMailer-API
      Description: 'API de PageGear Mailer'
      Role: !GetAtt LambdaExecutionRole.Arn
      Handler: index.handler
      MemorySize: 350
      Runtime: nodejs22.x
      AutoPublishAlias: !Ref Environment
      Timeout: !Ref TimeOut
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          PGCLOUD: "AWS4"


  PageGearMailerDevAlias:
    Type: AWS::Lambda::Alias
    Properties:
      Name: Dev
      FunctionVersion: $LATEST
      FunctionName: !Ref PageGearMailerApiFunction

  PageGearMailerDevPermission:
    Type: AWS::Lambda::Permission
    DependsOn: PageGearMailerDevAlias
    Properties:
      FunctionName: !Ref PageGearMailerDevAlias
      Action: lambda:InvokeFunctionUrl
      FunctionUrlAuthType: NONE
      Principal: "*"

  PageGearMailerDevUrl:
    Type: AWS::Lambda::Url
    DependsOn: PageGearMailerDevAlias
    Properties:
      AuthType: NONE
      Qualifier: Dev
      TargetFunctionArn: !Sub '${PageGearMailerApiFunction.Arn}'

  ApiCustomDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: api.correomasivo.com.co
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: PageGearMailer-API-Cert

  ApiCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        Aliases:
          - api.correomasivo.com.co
        Origins:
          - Id: LambdaFunctionUrlOrigin
            DomainName: !Select [2, !Split ['/', !GetAtt PageGearMailerApiFunctionUrl.FunctionUrl]]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
        DefaultCacheBehavior:
          TargetOriginId: LambdaFunctionUrlOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
        ViewerCertificate:
          AcmCertificateArn: !Ref ApiCustomDomainCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021


Outputs:
  PageGearMailer:
    Description: "ARN de la función PageGearMailer"
    Value: !Sub '${PageGearMailerApiFunction.Arn}:${Environment}'
    Export:
      Name: !Sub '${AWS::StackName}-PageGearMailer'
  PageGearMailerDev:
    Description: "ARN del alias DEV de la función PageGearMailer"
    Value: !Sub '${PageGearMailerApiFunction.Arn}:Dev'
    Export:
      Name: !Sub '${AWS::StackName}-PageGearMailerDev'
  PageGearMailerUrl:
    Description: "URL pública de la función PageGearMailer"
    Value: !GetAtt PageGearMailerApiFunctionUrl.FunctionUrl
    Export:
      Name: !Sub '${AWS::StackName}-PageGearMailerUrl'
  ApiCloudFrontDomain:
    Description: "Dominio de CloudFront para PageGearMailer"
    Value: !GetAtt ApiCloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-CloudFrontDomain'
