name: AWS Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install dependencies for API
        run: |
          cd api
          npm install
          
      - name: Install dependencies for Admin SPA
        run: |
          cd admin-spa/landing-admin
          npm install
          
      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: latest
          
      - name: Validate SAM template
        run: sam validate
          
      - name: SAM Build
        run: sam build --use-container
          
      - name: SAM Deploy
        env:
          AWS_REGION: us-east-1
        run: |
          sam deploy \
            --stack-name pagegear-mailer-api \
            --capabilities CAPABILITY_IAM \
            --region $AWS_REGION \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-s3 \
            --parameter-overrides Environment=Prod
